project:
  type: website
  output-dir: docs

quartodoc:
  package: receipt_processor

website:
  title: "Receipt Processor Docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: api.qmd
        text: API

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true